Vagrant.configure("2") do |config|

  # Box
  config.vm.box = "almalinux/10"
  #config.vm.box_version = "10.1.20260518"

  # Nome/hostname
  config.vm.hostname = "server1"

  # Desativar verificação automática de updates
  config.vm.box_check_update = false

  # Rede privada
  config.vm.network "private_network", ip: "192.168.56.10"

  # Desativa synced folder padrão
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider VirtualBox
  config.vm.provider "virtualbox" do |vb|
  
	# Recursos
    vb.name   = "server1"
    vb.memory = 2048
    vb.cpus   = 2
	# Video Memory (128 MB)
    vb.customize ["modifyvm", :id, "--vram", "128"]

    # Melhorias
    vb.gui = false

    # Evita conflitos de linked clones
    vb.linked_clone = true
  end

  # Provisionamento simples
  config.vm.provision "shell", inline: <<-SHELL
    dnf update -y
    dnf install -y epel-release
  SHELL

end
